### ISSUE TITLE
Add information on the source by Tria et al. and how this algorithm was adjusted

### ISSUE THREAD

**Issue by LinguList** [marisaKoe/rootingMAD#1]
I just saw that your thesis is online and was interested in how you dealt with MAD, as I know the authors well from my times in Düsseldorf (the senior author was then working there). As I cannot find any hints on the original source code, which is also available in Python, I'd suggest to add some information, also quote the source code (by adding their DOI) and specifically inform about the original package, where it can be found, and how it was adapted.

BTW: I'd also recommend to remove all global paths in your scripts, as this is some in my opinion sensitive information one would not want to share on GH.

**Comment by marisaKoe** [comment]
Thanks for the comment. I added the information in the ReadMe for full completeness.
